In [7]:
#### Before running code #####

#1. Download the PCN raw data received from Matt/Kelly and save it in 'current month' folder.
#2. Copy part numbers from Export Worksheet (in raw file) and paste in new excel sheet. Remove duplicates and save new file as Part#.
#3. Use Part# file for extracting restricted part info from cpr/. Open cpr/ --> import the part nbr list on left 



#### 3. Check file name, format, column headers, spellings etc in 'output template file' and 'PCN raw data' source file.
#### 4. Check if number of rows for unique part numbers = number of rows in Discrete EOL PNs sheet (in PCN raw data file).
#### 5. Verify Template and RawData file name, path.

In [8]:
import numpy as np
import pandas as pd
import datetime

In [9]:
# Reading Output template file - check file name, format, column headers, spellings etc
output = pd.read_excel("C:/Users/TE335168/Desktop/MIS Team/Adhoc/PCN report/MAIN SOURCE/PCN Report Template.xlsx")

# For reading PCN source file - check file name, format, column headers, spellings etc
file = pd.ExcelFile("C:/Users/TE335168/Desktop/MIS Team/Adhoc/PCN report/MAIN SOURCE/FY 2022/Oct 2022/Source.xlsx")
source = pd.read_excel(file, 'Export Worksheet')
discrete = pd.read_excel(file, 'Discrete EOL pns')

# Reading Restricted Part Info file
rest = pd.read_excel("C:/Users/TE335168/Desktop/MIS Team/Adhoc/PCN report/MAIN SOURCE/FY 2022/Oct 2022/Restricted.xlsx")

# Verifying source and output
print('Output')
display(output.head())
print("\n")
print('Source')
display(source.head(5))

# Dropping unnecessary cols, renaming cols
source = source.drop(['PCN_TYPE','PCN LT'], axis = 1)
source.rename(columns={'PCN Type': 'PCN_Type'}, inplace=True)

print("\n")
print('Updated Source')
source.head(5)

Output

Empty DataFrame
Columns: [PCN Number, Restricted Part?, PCN Type, Discontinued?, Reason for discontinuance, PART_NUMBER, Part Description, MOQ, BU, GPL, Replacement Part, MOQ Book Price, LT, PCN LT, LTB Days, Last Order Date, Can EOL be bought?, Last 12 mos POS, Last 12 mos CC]
Index: []

Source

,PART_NUMBER,PCN_NUMBER,PCN Type,PCN Action,PCN_DISTRIBUTED_DT,GENERAL_PRODUCT_DESCRIPTION,ST_CUST_ACCT_BASE,DESCRIPTION_OF_CHANGES,REASON_FOR_CHANGES,PCN_TYPE,...,LAST_ORDER_DATE,LAST_SHIP_DATE,FIRST_DATE_TO_SHIP,LAST_DATE_FOR_MIXED_SHIPMENTS,SALES_INDICATOR,DISCONTINUANCE_IND,PART_NUMBER.1,RELATED_PART_NUMBER,SALES_TERRITORY_NM,PCN LT
0,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,00133938,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,MANUF. LOC. CHG.,...,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Fernandes Mendes, Maria",NaN
1,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01378149,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,MANUF. LOC. CHG.,...,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,NaN,NaN
2,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,02888097,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,MANUF. LOC. CHG.,...,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Rodin, Alexander",NaN
3,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01407287,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,MANUF. LOC. CHG.,...,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Martins, Paulo",NaN
4,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01248810,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,MANUF. LOC. CHG.,...,NaN,NaN,2021-09-02 00:00:00.0,NaN,Indirect sale from reseller SEWS Romania S.R.L.,None,1801175-4,NaN,"Hamasaki, Mike",NaN

Updated Source

,PART_NUMBER,PCN_NUMBER,PCN_Type,PCN Action,PCN_DISTRIBUTED_DT,GENERAL_PRODUCT_DESCRIPTION,ST_CUST_ACCT_BASE,DESCRIPTION_OF_CHANGES,REASON_FOR_CHANGES,PCN_CLASSIFICATION,PCN_CREATOR_USERID,LAST_ORDER_DATE,LAST_SHIP_DATE,FIRST_DATE_TO_SHIP,LAST_DATE_FOR_MIXED_SHIPMENTS,SALES_INDICATOR,DISCONTINUANCE_IND,PART_NUMBER.1,RELATED_PART_NUMBER,SALES_TERRITORY_NM
0,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,00133938,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,Manufacturing Location Change,TE344006,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Fernandes Mendes, Maria"
1,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01378149,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,Manufacturing Location Change,TE344006,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,NaN
2,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,02888097,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,Manufacturing Location Change,TE344006,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Rodin, Alexander"
3,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01407287,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,Manufacturing Location Change,TE344006,NaN,NaN,2021-09-02 00:00:00.0,NaN,Direct sale,None,1801175-4,NaN,"Martins, Paulo"
4,1801175-4,P-21-021371,MLC,0,9/1/2021,NEPZ assemble production line transfer to K2 p...,01248810,NEPZ Assemble line transfer to K2 plant\r if c...,because of the company business strategy requi...,Manufacturing Location Change,TE344006,NaN,NaN,2021-09-02 00:00:00.0,NaN,Indirect sale from reseller SEWS Romania S.R.L.,None,1801175-4,NaN,"Hamasaki, Mike"

In [10]:
# Filtering df based on PCN Type = EOL
eol = source.loc[(source['PCN_Type'] == 'EOL')]
#print('eol filtered')
eol = eol[pd.notnull(eol['PART_NUMBER'])]
#display(eol.head(5))

# Getting unique list of part_numbers
prtnbr = eol['PART_NUMBER'].dropna().unique().tolist()
print("Unique part number count: ",len(prtnbr))

# Dropping duplicate values in filtered data keeping first value and resetting index
eol = eol.drop_duplicates(subset='PART_NUMBER', keep="first")
eol.reset_index(drop=True, inplace=True)
print("eol shape: ",eol.shape)
print("\n")
eol.head()

Unique part number count:  1141
eol shape:  (1141, 20)

,PART_NUMBER,PCN_NUMBER,PCN_Type,PCN Action,PCN_DISTRIBUTED_DT,GENERAL_PRODUCT_DESCRIPTION,ST_CUST_ACCT_BASE,DESCRIPTION_OF_CHANGES,REASON_FOR_CHANGES,PCN_CLASSIFICATION,PCN_CREATOR_USERID,LAST_ORDER_DATE,LAST_SHIP_DATE,FIRST_DATE_TO_SHIP,LAST_DATE_FOR_MIXED_SHIPMENTS,SALES_INDICATOR,DISCONTINUANCE_IND,PART_NUMBER.1,RELATED_PART_NUMBER,SALES_TERRITORY_NM
0,1-1418506-1,PCN-21-111887,EOL,Stocking Action,9/1/2021,AMP MCP 6.3 RECEPTACLE HOUSING 2 POS.,01299749,The listed part numbers 1-1418506-1 and 4-1418...,Product Discontinuance with Replacement,Discontinuance,FR0T0807,12/1/2021,2021-12-07 00:00:00.0,NaN,NaN,Direct sale,Discontinuance,1-1418506-1,NaN,NaN
1,6565129-1,PCN-21-111926,EOL,Stocking Action,9/1/2021,BATTERY CHARGER CABLE ASSY,01244479,"THE CUSTOMER HAVEN'T DEMAND,EOL","THE CUSTOMER HAVEN'T DEMAND,EOL",Discontinuance,FR017471,11/24/2021,2021-11-25 00:00:00.0,NaN,NaN,Agreement,Discontinuance,6565129-1,NaN,Solution Ctr - Asia Team
2,4-1418506-1,PCN-21-111887,EOL,Stocking Action,9/1/2021,AMP MCP 6.3 RECEPTACLE HOUSING 2 POS.,03076409,The listed part numbers 1-1418506-1 and 4-1418...,Product Discontinuance with Replacement,Discontinuance,FR0T0807,12/1/2021,2021-12-07 00:00:00.0,NaN,NaN,Direct sale,Discontinuance,4-1418506-1,NaN,"Su, Suger"
3,6-528041-0,E-21-007334,EOL,"No stocking action, distributor update system",9/1/2021,LEGACY DIE SETS SUPERCEDED Action for planer A...,01309094,The following part numbers are being obsolete...,"Discontinuance. Dear Customer, You are receivi...",Discontinuance,EG010896,9/2/2021,2021-09-03 00:00:00.0,NaN,NaN,Direct sale,Discontinuance,6-528041-0,NaN,"Stan, Sebastian"
4,1934118-1,PCN-21-111851,EOL,Stocking Action,9/2/2021,HMZD Connectors,01247807,The listed part numbers are being discontinued...,Product Discontinuance,Discontinuance,TE423832,11/30/2021,2021-12-31 00:00:00.0,NaN,NaN,Agreement,Discontinuance,1934118-1,NaN,"Aoshima, Takuya"

In [11]:
#Updating values in output template
output['PART_NUMBER'] = eol['PART_NUMBER']
output['PCN Type'] = 'EOL'
output['Discontinued?'] = 'Yes'
output['PCN Number'] = eol['PCN_NUMBER']
output['Reason for discontinuance'] = eol['REASON_FOR_CHANGES']
output['Part Description'] = eol['GENERAL_PRODUCT_DESCRIPTION']
output['Last Order Date'] = eol['LAST_ORDER_DATE']

In [12]:
# Verifying Discrete EOL Tab
print(discrete.shape)

# Check if number of rows for unique part numbers = number of rows in Discrete EOL PNs sheet
# Updating column names
discrete.rename(columns={'P/N': 'PART_NUMBER', 'Replacement Part': 'Replacement', 'PCN LT': 'PCN_LT'}, inplace=True)
display(discrete.head())

(1141, 9)

,PART_NUMBER,CPR Status,BU,Replacement,Replacement Y/N,Last order date,Last order date Y/N,PCN_LT,More than 30 days notice Y/N
0,1-1418506-1,RESTRICTED SALES,AUT - Automotive,0,No,12/1/2021,Yes,91,Yes
1,6565129-1,RESTRICTED SALES,DND - Data and Devices,0,No,11/24/2021,Yes,84,Yes
2,4-1418506-1,RESTRICTED SALES,AUT - Automotive,0,No,12/1/2021,Yes,91,Yes
3,6-528041-0,GENERAL SALES,ASG - Application Tooling,2234181-1,Yes,9/2/2021,Yes,1,No
4,1934118-1,GENERAL SALES,DND - Data and Devices,0,No,11/30/2021,Yes,89,Yes

In [13]:
# Updating output template
#output['MOQ'] = discrete['MOQ'] check if MOQ is present in Discrete
#output['GPL'] = discrete['GPL'] check if GPL is present in Discrete
output['BU'] = discrete['BU']
output['Replacement Part'] = discrete['Replacement']
output['PCN LT'] = discrete['PCN_LT']

In [14]:
# Input current date for calculating 'Can EOL be bought?'
date_entry = input('Enter a date in YYYY-MM-DD format')
year, month, day = map(int, date_entry.split('-'))
date = datetime.date(year, month, day)
date = pd.to_datetime(date)
date
#formatted_date = datetime.date.strftime(date1, "%m/%d/%Y")

Enter a date in YYYY-MM-DD format2021-11-25

Timestamp('2021-11-25 00:00:00')

In [15]:
# Converting data type of Last Order Date col from string to datetime and removing //
output['Last Order Date'] = np.where(output['Last Order Date'] == '//', 0 , output['Last Order Date'])
output['Last Order Date'] = pd.to_datetime(output['Last Order Date'])

In [16]:
# Appending status list based on conditions for 'Can EOL be bought?'
date1 = pd.to_datetime('1970-01-01')

status = []
for row in  output['Last Order Date']:
    if row > date:
        status.append('Yes')
    elif row == date1:
        status.append('Unknown')
    else:
        status.append('No')

In [17]:
#Updating data in output template for replacement part and Last order Date in MM-DD-YYYY format
output['Can EOL be bought?'] = status
output['Replacement Part'] = np.where(output['Replacement Part'] == 0, 'N/A', output['Replacement Part'])
output['Last Order Date'] = output['Last Order Date'].dt.date
output['Last Order Date'] = pd.to_datetime(output['Last Order Date']).dt.strftime('%m/%d/%Y')
output['Last Order Date'] = np.where(output['Last Order Date'] == '01/01/1970', '-' , output['Last Order Date'])

In [18]:
# For restricted part information
display(rest.head(2))
rest.shape

,TCPN,Sales Intent,Part Description,Part Status,Part Rev,RDO,Production Drawing,Project Nbr,Product Code
0,1-1418497-0,GENERAL SALES,DIA 1.5 SOCK CON TERMINAL,Production,A,730,1418497,NaN,M065
1,1-1564369-3,RESTRICTED SALES,"LOCKABLE SQ,CABLE ASSY,CODB",Production,C,870,1564369,NaN,A212

(1141, 9)

In [19]:
rest = rest.drop(['Part Description','Part Status','Part Rev','RDO','Production Drawing','Project Nbr','Product Code'], axis=1)
rest['Restricted Part?'] = np.where(rest['Sales Intent'] == 'RESTRICTED SALES',"Yes","No")
rest.rename(columns={'TCPN': 'PART_NUMBER'}, inplace=True)
rest = rest.drop(['Sales Intent'],axis=1)
output = output.drop(['Restricted Part?'],axis=1)
output = pd.merge(output, rest, on ='PART_NUMBER', how ='left')

In [20]:
#cols = list(output.columns.values)
#cols

In [21]:
#Changing order of columns
output = output[['PCN Number','Restricted Part?',
 'PCN Type',
 'Discontinued?',
 'Reason for discontinuance',
 'PART_NUMBER',
 'Part Description',
 'MOQ',
 'BU',
 'GPL',
 'Replacement Part',
 'MOQ Book Price',
 'LT',
 'PCN LT',
 'LTB Days',
 'Last Order Date',
 'Can EOL be bought?',
 'Last 12 mos POS',
 'Last 12 mos CC']]

In [22]:
#Writing to excel output file
writer = pd.ExcelWriter('PCN EOL ACTION LIST.xlsx', engine='xlsxwriter')
output.to_excel(writer, sheet_name='Action List')
writer.save()